[2023-11-21T01:21:13.740+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: outcomes_dag.load scheduled__2023-11-16T00:00:00+00:00 [queued]>
[2023-11-21T01:21:13.773+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: outcomes_dag.load scheduled__2023-11-16T00:00:00+00:00 [queued]>
[2023-11-21T01:21:13.781+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-11-21T01:21:13.832+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): load> on 2023-11-16 00:00:00+00:00
[2023-11-21T01:21:13.851+0000] {standard_task_runner.py:57} INFO - Started process 277 to run task
[2023-11-21T01:21:13.881+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'outcomes_dag', 'load', 'scheduled__2023-11-16T00:00:00+00:00', '--job-id', '53', '--raw', '--subdir', 'DAGS_FOLDER/outcomes_dag.py', '--cfg-path', '/tmp/tmple9ji_6t']
[2023-11-21T01:21:13.930+0000] {standard_task_runner.py:85} INFO - Job 53: Subtask load
[2023-11-21T01:21:14.170+0000] {task_command.py:416} INFO - Running <TaskInstance: outcomes_dag.load scheduled__2023-11-16T00:00:00+00:00 [running]> on host f31a30014ab0
[2023-11-21T01:21:18.316+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='outcomes_dag' AIRFLOW_CTX_TASK_ID='load' AIRFLOW_CTX_EXECUTION_DATE='2023-11-16T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-16T00:00:00+00:00'
[2023-11-21T01:21:18.485+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ETL/load.py", line 11, in load_data
    data_to_staging(filename, engine)
  File "/opt/airflow/dags/ETL/load.py", line 19, in data_to_staging
    data = pd.read_parquet(filename)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parquet.py", line 509, in read_parquet
    return impl.read(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parquet.py", line 220, in read
    path_or_handle, handles, kwargs["filesystem"] = _get_path_or_handle(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parquet.py", line 110, in _get_path_or_handle
    handles = get_handle(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/common.py", line 868, in get_handle
    handle = open(handle, ioargs.mode)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/data/2023-11-16/processed/transformed_shelter_data.parquet'
[2023-11-21T01:21:18.531+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=outcomes_dag, task_id=load, execution_date=20231116T000000, start_date=20231121T012113, end_date=20231121T012118
[2023-11-21T01:21:18.574+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 53 for task load ([Errno 2] No such file or directory: '/opt/airflow/data/2023-11-16/processed/transformed_shelter_data.parquet'; 277)
[2023-11-21T01:21:18.770+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-21T01:21:19.070+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-11-21T02:36:31.830+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: outcomes_dag.load scheduled__2023-11-16T00:00:00+00:00 [queued]>
[2023-11-21T02:36:31.847+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: outcomes_dag.load scheduled__2023-11-16T00:00:00+00:00 [queued]>
[2023-11-21T02:36:31.850+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-11-21T02:36:31.877+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): load> on 2023-11-16 00:00:00+00:00
[2023-11-21T02:36:31.899+0000] {standard_task_runner.py:57} INFO - Started process 288 to run task
[2023-11-21T02:36:31.920+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'outcomes_dag', 'load', 'scheduled__2023-11-16T00:00:00+00:00', '--job-id', '51', '--raw', '--subdir', 'DAGS_FOLDER/outcomes_dag.py', '--cfg-path', '/tmp/tmpt9drln91']
[2023-11-21T02:36:31.930+0000] {standard_task_runner.py:85} INFO - Job 51: Subtask load
[2023-11-21T02:36:32.175+0000] {task_command.py:416} INFO - Running <TaskInstance: outcomes_dag.load scheduled__2023-11-16T00:00:00+00:00 [running]> on host b875fa978b1e
[2023-11-21T02:36:33.551+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='outcomes_dag' AIRFLOW_CTX_TASK_ID='load' AIRFLOW_CTX_EXECUTION_DATE='2023-11-16T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-16T00:00:00+00:00'
[2023-11-21T02:36:33.617+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ETL/load.py", line 11, in load_data
    data_to_staging(filename, engine)
  File "/opt/airflow/dags/ETL/load.py", line 19, in data_to_staging
    data = pd.read_parquet(filename)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parquet.py", line 509, in read_parquet
    return impl.read(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parquet.py", line 220, in read
    path_or_handle, handles, kwargs["filesystem"] = _get_path_or_handle(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parquet.py", line 110, in _get_path_or_handle
    handles = get_handle(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/common.py", line 868, in get_handle
    handle = open(handle, ioargs.mode)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/data/2023-11-16/processed/transformed_shelter_data.parquet'
[2023-11-21T02:36:33.709+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=outcomes_dag, task_id=load, execution_date=20231116T000000, start_date=20231121T023631, end_date=20231121T023633
[2023-11-21T02:36:33.780+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 51 for task load ([Errno 2] No such file or directory: '/opt/airflow/data/2023-11-16/processed/transformed_shelter_data.parquet'; 288)
[2023-11-21T02:36:33.891+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-21T02:36:33.972+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-11-21T03:16:14.803+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: outcomes_dag.load scheduled__2023-11-16T00:00:00+00:00 [queued]>
[2023-11-21T03:16:14.816+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: outcomes_dag.load scheduled__2023-11-16T00:00:00+00:00 [queued]>
[2023-11-21T03:16:14.816+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-11-21T03:16:14.828+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): load> on 2023-11-16 00:00:00+00:00
[2023-11-21T03:16:14.837+0000] {standard_task_runner.py:57} INFO - Started process 127 to run task
[2023-11-21T03:16:14.844+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'outcomes_dag', 'load', 'scheduled__2023-11-16T00:00:00+00:00', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/outcomes_dag.py', '--cfg-path', '/tmp/tmp269liwzm']
[2023-11-21T03:16:14.848+0000] {standard_task_runner.py:85} INFO - Job 18: Subtask load
[2023-11-21T03:16:14.912+0000] {task_command.py:416} INFO - Running <TaskInstance: outcomes_dag.load scheduled__2023-11-16T00:00:00+00:00 [running]> on host 33d8c5494200
[2023-11-21T03:16:15.404+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='outcomes_dag' AIRFLOW_CTX_TASK_ID='load' AIRFLOW_CTX_EXECUTION_DATE='2023-11-16T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-16T00:00:00+00:00'
[2023-11-21T03:16:15.864+0000] {logging_mixin.py:154} INFO - Data is in Staging Table...
[2023-11-21T03:16:15.867+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ETL/load.py", line 13, in load_data
    execute_sql_script(engine)
  File "/opt/airflow/dags/ETL/load.py", line 38, in execute_sql_script
    with open(script_path, 'r') as file:
FileNotFoundError: [Errno 2] No such file or directory: 'data_insertion.sql'
[2023-11-21T03:16:15.887+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=outcomes_dag, task_id=load, execution_date=20231116T000000, start_date=20231121T031614, end_date=20231121T031615
[2023-11-21T03:16:15.901+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 18 for task load ([Errno 2] No such file or directory: 'data_insertion.sql'; 127)
[2023-11-21T03:16:15.953+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-21T03:16:16.003+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-11-22T03:22:54.551+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: outcomes_dag.Load scheduled__2023-11-16T00:00:00+00:00 [queued]>
[2023-11-22T03:22:54.567+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: outcomes_dag.Load scheduled__2023-11-16T00:00:00+00:00 [queued]>
[2023-11-22T03:22:54.580+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-11-22T03:22:54.612+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): Load> on 2023-11-16 00:00:00+00:00
[2023-11-22T03:22:54.629+0000] {standard_task_runner.py:57} INFO - Started process 115 to run task
[2023-11-22T03:22:54.669+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'outcomes_dag', 'Load', 'scheduled__2023-11-16T00:00:00+00:00', '--job-id', '20', '--raw', '--subdir', 'DAGS_FOLDER/outcomes_dag.py', '--cfg-path', '/tmp/tmpw01z2o3m']
[2023-11-22T03:22:54.686+0000] {standard_task_runner.py:85} INFO - Job 20: Subtask Load
[2023-11-22T03:22:54.980+0000] {task_command.py:416} INFO - Running <TaskInstance: outcomes_dag.Load scheduled__2023-11-16T00:00:00+00:00 [running]> on host cf56a4e96859
[2023-11-22T03:22:55.171+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='outcomes_dag' AIRFLOW_CTX_TASK_ID='Load' AIRFLOW_CTX_EXECUTION_DATE='2023-11-16T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-16T00:00:00+00:00'
[2023-11-22T03:22:55.177+0000] {logging_mixin.py:154} INFO - Getting data from Cloud Storage
[2023-11-22T03:22:56.016+0000] {logging_mixin.py:154} INFO - Data is in Staging Table...
[2023-11-22T03:22:56.024+0000] {logging_mixin.py:154} INFO - Data is Loaded into Fact & Dim Tables
[2023-11-22T03:22:56.024+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-11-22T03:22:56.033+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=outcomes_dag, task_id=Load, execution_date=20231116T000000, start_date=20231122T032254, end_date=20231122T032256
[2023-11-22T03:22:56.056+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-11-22T03:22:56.100+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-11-22T03:55:57.200+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: outcomes_dag.Load scheduled__2023-11-16T00:00:00+00:00 [queued]>
[2023-11-22T03:55:57.216+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: outcomes_dag.Load scheduled__2023-11-16T00:00:00+00:00 [queued]>
[2023-11-22T03:55:57.219+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-11-22T03:55:57.240+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): Load> on 2023-11-16 00:00:00+00:00
[2023-11-22T03:55:57.259+0000] {standard_task_runner.py:57} INFO - Started process 125 to run task
[2023-11-22T03:55:57.288+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'outcomes_dag', 'Load', 'scheduled__2023-11-16T00:00:00+00:00', '--job-id', '22', '--raw', '--subdir', 'DAGS_FOLDER/outcomes_dag.py', '--cfg-path', '/tmp/tmpqwb7by9h']
[2023-11-22T03:55:57.300+0000] {standard_task_runner.py:85} INFO - Job 22: Subtask Load
[2023-11-22T03:55:57.448+0000] {task_command.py:416} INFO - Running <TaskInstance: outcomes_dag.Load scheduled__2023-11-16T00:00:00+00:00 [running]> on host cf936e748923
[2023-11-22T03:55:57.571+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='outcomes_dag' AIRFLOW_CTX_TASK_ID='Load' AIRFLOW_CTX_EXECUTION_DATE='2023-11-16T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-16T00:00:00+00:00'
[2023-11-22T03:55:57.573+0000] {logging_mixin.py:154} INFO - Getting data from Cloud Storage
[2023-11-22T03:55:58.628+0000] {logging_mixin.py:154} INFO - Data is in Staging Table...
[2023-11-22T03:55:58.637+0000] {logging_mixin.py:154} INFO - Data is Loaded into Fact & Dim Tables
[2023-11-22T03:55:58.637+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-11-22T03:55:58.651+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=outcomes_dag, task_id=Load, execution_date=20231116T000000, start_date=20231122T035557, end_date=20231122T035558
[2023-11-22T03:55:58.675+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-11-22T03:55:58.698+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-11-22T05:47:52.421+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: outcomes_dag.Load scheduled__2023-11-16T00:00:00+00:00 [queued]>
[2023-11-22T05:47:52.443+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: outcomes_dag.Load scheduled__2023-11-16T00:00:00+00:00 [queued]>
[2023-11-22T05:47:52.457+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 4
[2023-11-22T05:47:52.473+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): Load> on 2023-11-16 00:00:00+00:00
[2023-11-22T05:47:52.489+0000] {standard_task_runner.py:57} INFO - Started process 203 to run task
[2023-11-22T05:47:52.496+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'outcomes_dag', 'Load', 'scheduled__2023-11-16T00:00:00+00:00', '--job-id', '30', '--raw', '--subdir', 'DAGS_FOLDER/outcomes_dag.py', '--cfg-path', '/tmp/tmp5rl3veky']
[2023-11-22T05:47:52.511+0000] {standard_task_runner.py:85} INFO - Job 30: Subtask Load
[2023-11-22T05:47:52.596+0000] {task_command.py:416} INFO - Running <TaskInstance: outcomes_dag.Load scheduled__2023-11-16T00:00:00+00:00 [running]> on host 6e2e77b078ed
[2023-11-22T05:47:52.659+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='outcomes_dag' AIRFLOW_CTX_TASK_ID='Load' AIRFLOW_CTX_EXECUTION_DATE='2023-11-16T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-16T00:00:00+00:00'
[2023-11-22T05:47:52.661+0000] {logging_mixin.py:154} INFO - Getting data from Cloud Storage
[2023-11-22T05:47:53.318+0000] {logging_mixin.py:154} INFO - Data is in Staging Table...
[2023-11-22T05:47:53.318+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-11-22T05:47:53.327+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=outcomes_dag, task_id=Load, execution_date=20231116T000000, start_date=20231122T054752, end_date=20231122T054753
[2023-11-22T05:47:53.354+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-11-22T06:09:47.559+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: outcomes_dag.Load scheduled__2023-11-16T00:00:00+00:00 [queued]>
[2023-11-22T06:09:47.576+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: outcomes_dag.Load scheduled__2023-11-16T00:00:00+00:00 [queued]>
[2023-11-22T06:09:47.578+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 4
[2023-11-22T06:09:47.604+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): Load> on 2023-11-16 00:00:00+00:00
[2023-11-22T06:09:47.622+0000] {standard_task_runner.py:57} INFO - Started process 139 to run task
[2023-11-22T06:09:47.672+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'outcomes_dag', 'Load', 'scheduled__2023-11-16T00:00:00+00:00', '--job-id', '24', '--raw', '--subdir', 'DAGS_FOLDER/outcomes_dag.py', '--cfg-path', '/tmp/tmpjs4jmf9f']
[2023-11-22T06:09:47.699+0000] {standard_task_runner.py:85} INFO - Job 24: Subtask Load
[2023-11-22T06:09:47.853+0000] {task_command.py:416} INFO - Running <TaskInstance: outcomes_dag.Load scheduled__2023-11-16T00:00:00+00:00 [running]> on host ded66acd9c7f
[2023-11-22T06:09:47.964+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='outcomes_dag' AIRFLOW_CTX_TASK_ID='Load' AIRFLOW_CTX_EXECUTION_DATE='2023-11-16T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-16T00:00:00+00:00'
[2023-11-22T06:09:47.966+0000] {logging_mixin.py:154} INFO - Getting data from Cloud Storage
[2023-11-22T06:09:48.575+0000] {logging_mixin.py:154} INFO - Data is in Staging Table...
[2023-11-22T06:09:48.576+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-11-22T06:09:48.584+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=outcomes_dag, task_id=Load, execution_date=20231116T000000, start_date=20231122T060947, end_date=20231122T060948
[2023-11-22T06:09:48.605+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-11-22T06:19:04.562+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: outcomes_dag.Load scheduled__2023-11-16T00:00:00+00:00 [queued]>
[2023-11-22T06:19:04.605+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: outcomes_dag.Load scheduled__2023-11-16T00:00:00+00:00 [queued]>
[2023-11-22T06:19:04.611+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 4
[2023-11-22T06:19:04.634+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): Load> on 2023-11-16 00:00:00+00:00
[2023-11-22T06:19:04.671+0000] {standard_task_runner.py:57} INFO - Started process 123 to run task
[2023-11-22T06:19:04.702+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'outcomes_dag', 'Load', 'scheduled__2023-11-16T00:00:00+00:00', '--job-id', '20', '--raw', '--subdir', 'DAGS_FOLDER/outcomes_dag.py', '--cfg-path', '/tmp/tmpdjus1z_l']
[2023-11-22T06:19:04.721+0000] {standard_task_runner.py:85} INFO - Job 20: Subtask Load
[2023-11-22T06:19:04.860+0000] {task_command.py:416} INFO - Running <TaskInstance: outcomes_dag.Load scheduled__2023-11-16T00:00:00+00:00 [running]> on host 836b7d8b8a64
[2023-11-22T06:19:04.970+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='outcomes_dag' AIRFLOW_CTX_TASK_ID='Load' AIRFLOW_CTX_EXECUTION_DATE='2023-11-16T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-16T00:00:00+00:00'
[2023-11-22T06:19:04.975+0000] {logging_mixin.py:154} INFO - Getting data from Cloud Storage
[2023-11-22T06:19:05.987+0000] {logging_mixin.py:154} INFO - Data is in Staging Table...
[2023-11-22T06:19:05.987+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-11-22T06:19:06.002+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=outcomes_dag, task_id=Load, execution_date=20231116T000000, start_date=20231122T061904, end_date=20231122T061906
[2023-11-22T06:19:06.057+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-11-22T07:15:08.280+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: outcomes_dag.Load scheduled__2023-11-16T00:00:00+00:00 [queued]>
[2023-11-22T07:15:08.290+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: outcomes_dag.Load scheduled__2023-11-16T00:00:00+00:00 [queued]>
[2023-11-22T07:15:08.292+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 4
[2023-11-22T07:15:08.322+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): Load> on 2023-11-16 00:00:00+00:00
[2023-11-22T07:15:08.334+0000] {standard_task_runner.py:57} INFO - Started process 129 to run task
[2023-11-22T07:15:08.351+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'outcomes_dag', 'Load', 'scheduled__2023-11-16T00:00:00+00:00', '--job-id', '26', '--raw', '--subdir', 'DAGS_FOLDER/outcomes_dag.py', '--cfg-path', '/tmp/tmpqt6yl8dg']
[2023-11-22T07:15:08.360+0000] {standard_task_runner.py:85} INFO - Job 26: Subtask Load
[2023-11-22T07:15:08.411+0000] {task_command.py:416} INFO - Running <TaskInstance: outcomes_dag.Load scheduled__2023-11-16T00:00:00+00:00 [running]> on host 011245d9ad62
[2023-11-22T07:15:08.466+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='outcomes_dag' AIRFLOW_CTX_TASK_ID='Load' AIRFLOW_CTX_EXECUTION_DATE='2023-11-16T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-16T00:00:00+00:00'
[2023-11-22T07:15:08.467+0000] {logging_mixin.py:154} INFO - Getting data from Cloud Storage
[2023-11-22T07:15:10.003+0000] {logging_mixin.py:154} INFO - Data is in Staging Table...
[2023-11-22T07:15:10.004+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-11-22T07:15:10.016+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=outcomes_dag, task_id=Load, execution_date=20231116T000000, start_date=20231122T071508, end_date=20231122T071510
[2023-11-22T07:15:10.092+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-11-22T07:54:05.281+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: outcomes_dag.Load scheduled__2023-11-16T00:00:00+00:00 [queued]>
[2023-11-22T07:54:05.348+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: outcomes_dag.Load scheduled__2023-11-16T00:00:00+00:00 [queued]>
[2023-11-22T07:54:05.350+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 4
[2023-11-22T07:54:05.385+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): Load> on 2023-11-16 00:00:00+00:00
[2023-11-22T07:54:05.415+0000] {standard_task_runner.py:57} INFO - Started process 359 to run task
[2023-11-22T07:54:05.483+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'outcomes_dag', 'Load', 'scheduled__2023-11-16T00:00:00+00:00', '--job-id', '42', '--raw', '--subdir', 'DAGS_FOLDER/outcomes_dag.py', '--cfg-path', '/tmp/tmph6b8k747']
[2023-11-22T07:54:05.532+0000] {standard_task_runner.py:85} INFO - Job 42: Subtask Load
[2023-11-22T07:54:05.838+0000] {task_command.py:416} INFO - Running <TaskInstance: outcomes_dag.Load scheduled__2023-11-16T00:00:00+00:00 [running]> on host 6318e996d951
[2023-11-22T07:54:06.165+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='outcomes_dag' AIRFLOW_CTX_TASK_ID='Load' AIRFLOW_CTX_EXECUTION_DATE='2023-11-16T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-16T00:00:00+00:00'
[2023-11-22T07:54:06.182+0000] {logging_mixin.py:154} INFO - Getting data from Cloud Storage
[2023-11-22T07:54:08.287+0000] {logging_mixin.py:154} INFO - Data is in Staging Table...
[2023-11-22T07:54:08.300+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-11-22T07:54:08.397+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=outcomes_dag, task_id=Load, execution_date=20231116T000000, start_date=20231122T075405, end_date=20231122T075408
[2023-11-22T07:54:09.504+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-11-23T01:49:43.560+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: outcomes_dag.Load scheduled__2023-11-16T00:00:00+00:00 [queued]>
[2023-11-23T01:49:43.587+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: outcomes_dag.Load scheduled__2023-11-16T00:00:00+00:00 [queued]>
[2023-11-23T01:49:43.594+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 4
[2023-11-23T01:49:43.675+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): Load> on 2023-11-16 00:00:00+00:00
[2023-11-23T01:49:43.697+0000] {standard_task_runner.py:57} INFO - Started process 212 to run task
[2023-11-23T01:49:43.772+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'outcomes_dag', 'Load', 'scheduled__2023-11-16T00:00:00+00:00', '--job-id', '47', '--raw', '--subdir', 'DAGS_FOLDER/outcomes_dag.py', '--cfg-path', '/tmp/tmpxlzy9a_p']
[2023-11-23T01:49:43.870+0000] {standard_task_runner.py:85} INFO - Job 47: Subtask Load
[2023-11-23T01:49:44.093+0000] {task_command.py:416} INFO - Running <TaskInstance: outcomes_dag.Load scheduled__2023-11-16T00:00:00+00:00 [running]> on host d15d3caa5b00
[2023-11-23T01:49:44.396+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='outcomes_dag' AIRFLOW_CTX_TASK_ID='Load' AIRFLOW_CTX_EXECUTION_DATE='2023-11-16T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-16T00:00:00+00:00'
[2023-11-23T01:49:44.402+0000] {logging_mixin.py:154} INFO - Getting data from Cloud Storage
[2023-11-23T01:49:45.500+0000] {logging_mixin.py:154} INFO - Data is in Staging Table...
[2023-11-23T01:49:45.511+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-11-23T01:49:45.584+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=outcomes_dag, task_id=Load, execution_date=20231116T000000, start_date=20231123T014943, end_date=20231123T014945
[2023-11-23T01:49:45.765+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-11-23T01:58:44.104+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: outcomes_dag.Load scheduled__2023-11-16T00:00:00+00:00 [queued]>
[2023-11-23T01:58:44.150+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: outcomes_dag.Load scheduled__2023-11-16T00:00:00+00:00 [queued]>
[2023-11-23T01:58:44.151+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 4
[2023-11-23T01:58:44.171+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): Load> on 2023-11-16 00:00:00+00:00
[2023-11-23T01:58:44.207+0000] {standard_task_runner.py:57} INFO - Started process 120 to run task
[2023-11-23T01:58:44.217+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'outcomes_dag', 'Load', 'scheduled__2023-11-16T00:00:00+00:00', '--job-id', '21', '--raw', '--subdir', 'DAGS_FOLDER/outcomes_dag.py', '--cfg-path', '/tmp/tmpsaoubibx']
[2023-11-23T01:58:44.233+0000] {standard_task_runner.py:85} INFO - Job 21: Subtask Load
[2023-11-23T01:58:44.310+0000] {task_command.py:416} INFO - Running <TaskInstance: outcomes_dag.Load scheduled__2023-11-16T00:00:00+00:00 [running]> on host 3cdc572bc068
[2023-11-23T01:58:44.405+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='outcomes_dag' AIRFLOW_CTX_TASK_ID='Load' AIRFLOW_CTX_EXECUTION_DATE='2023-11-16T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-16T00:00:00+00:00'
[2023-11-23T01:58:44.408+0000] {logging_mixin.py:154} INFO - Getting data from Cloud Storage
[2023-11-23T01:58:45.097+0000] {logging_mixin.py:154} INFO - Data is in Staging Table...
[2023-11-23T01:58:45.098+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-11-23T01:58:45.115+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=outcomes_dag, task_id=Load, execution_date=20231116T000000, start_date=20231123T015844, end_date=20231123T015845
[2023-11-23T01:58:45.174+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-11-23T02:59:44.363+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: outcomes_dag.Load scheduled__2023-11-16T00:00:00+00:00 [queued]>
[2023-11-23T02:59:44.385+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: outcomes_dag.Load scheduled__2023-11-16T00:00:00+00:00 [queued]>
[2023-11-23T02:59:44.388+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 4
[2023-11-23T02:59:45.121+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): Load> on 2023-11-16 00:00:00+00:00
[2023-11-23T02:59:45.140+0000] {standard_task_runner.py:57} INFO - Started process 168 to run task
[2023-11-23T02:59:45.157+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'outcomes_dag', 'Load', 'scheduled__2023-11-16T00:00:00+00:00', '--job-id', '22', '--raw', '--subdir', 'DAGS_FOLDER/outcomes_dag.py', '--cfg-path', '/tmp/tmpb_1xufwb']
[2023-11-23T02:59:45.163+0000] {standard_task_runner.py:85} INFO - Job 22: Subtask Load
[2023-11-23T02:59:45.257+0000] {task_command.py:416} INFO - Running <TaskInstance: outcomes_dag.Load scheduled__2023-11-16T00:00:00+00:00 [running]> on host 1268bd8e5db0
[2023-11-23T02:59:45.329+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='outcomes_dag' AIRFLOW_CTX_TASK_ID='Load' AIRFLOW_CTX_EXECUTION_DATE='2023-11-16T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-16T00:00:00+00:00'
[2023-11-23T02:59:45.332+0000] {logging_mixin.py:154} INFO - Getting data from Cloud Storage
[2023-11-23T02:59:46.080+0000] {logging_mixin.py:154} INFO - Data is in Staging Area...
[2023-11-23T02:59:46.081+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-11-23T02:59:46.100+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=outcomes_dag, task_id=Load, execution_date=20231116T000000, start_date=20231123T025944, end_date=20231123T025946
[2023-11-23T02:59:46.145+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-11-23T03:40:52.682+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: outcomes_dag.Load scheduled__2023-11-16T00:00:00+00:00 [queued]>
[2023-11-23T03:40:52.696+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: outcomes_dag.Load scheduled__2023-11-16T00:00:00+00:00 [queued]>
[2023-11-23T03:40:52.696+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 4
[2023-11-23T03:40:52.715+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): Load> on 2023-11-16 00:00:00+00:00
[2023-11-23T03:40:52.726+0000] {standard_task_runner.py:57} INFO - Started process 206 to run task
[2023-11-23T03:40:52.751+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'outcomes_dag', 'Load', 'scheduled__2023-11-16T00:00:00+00:00', '--job-id', '50', '--raw', '--subdir', 'DAGS_FOLDER/outcomes_dag.py', '--cfg-path', '/tmp/tmpfvxfo166']
[2023-11-23T03:40:52.765+0000] {standard_task_runner.py:85} INFO - Job 50: Subtask Load
[2023-11-23T03:40:52.944+0000] {task_command.py:416} INFO - Running <TaskInstance: outcomes_dag.Load scheduled__2023-11-16T00:00:00+00:00 [running]> on host e647c96745b0
[2023-11-23T03:40:53.128+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='outcomes_dag' AIRFLOW_CTX_TASK_ID='Load' AIRFLOW_CTX_EXECUTION_DATE='2023-11-16T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-16T00:00:00+00:00'
[2023-11-23T03:40:53.137+0000] {logging_mixin.py:154} INFO - Getting data from Cloud Storage
[2023-11-23T03:40:54.112+0000] {logging_mixin.py:154} INFO - Data is in Staging Area...
[2023-11-23T03:40:54.113+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-11-23T03:40:54.166+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=outcomes_dag, task_id=Load, execution_date=20231116T000000, start_date=20231123T034052, end_date=20231123T034054
[2023-11-23T03:40:54.287+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
