[2023-11-23T01:05:21.142+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: outcomes_dag.Initialize_wharehouse_schema scheduled__2023-11-19T00:00:00+00:00 [queued]>
[2023-11-23T01:05:21.146+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: outcomes_dag.Initialize_wharehouse_schema scheduled__2023-11-19T00:00:00+00:00 [queued]>
[2023-11-23T01:05:21.146+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 2
[2023-11-23T01:05:21.151+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): Initialize_wharehouse_schema> on 2023-11-19 00:00:00+00:00
[2023-11-23T01:05:21.157+0000] {standard_task_runner.py:57} INFO - Started process 974 to run task
[2023-11-23T01:05:21.160+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'outcomes_dag', 'Initialize_wharehouse_schema', 'scheduled__2023-11-19T00:00:00+00:00', '--job-id', '174', '--raw', '--subdir', 'DAGS_FOLDER/outcomes_dag.py', '--cfg-path', '/tmp/tmpsnr64kxm']
[2023-11-23T01:05:21.163+0000] {standard_task_runner.py:85} INFO - Job 174: Subtask Initialize_wharehouse_schema
[2023-11-23T01:05:21.197+0000] {task_command.py:416} INFO - Running <TaskInstance: outcomes_dag.Initialize_wharehouse_schema scheduled__2023-11-19T00:00:00+00:00 [running]> on host 75913536581a
[2023-11-23T01:05:21.241+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='outcomes_dag' AIRFLOW_CTX_TASK_ID='Initialize_wharehouse_schema' AIRFLOW_CTX_EXECUTION_DATE='2023-11-19T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-19T00:00:00+00:00'
[2023-11-23T01:05:21.813+0000] {load.py:19} INFO - SQL statement executed successfully: -- CREATE STAGING TABLE (CATCHES ALL TRANSFORMED DATA)
CREATE OR REPLACE TABLE shelter_warehouse_schema.outcomes_staging (
    `Animal ID` STRING,
    `Outcome` STRING,
    `Date ID` INT64,
    `Day` INT64,
    `Month` INT64,
    `Year` INT64,
    `Reproductive Status` STRING,
    `Name` STRING,
    `Animal Type` STRING,
    `Breed` STRING,
    `Color` STRING,
    `Sex` STRING,
    `DOB` DATE
)
[2023-11-23T01:05:22.152+0000] {load.py:19} INFO - SQL statement executed successfully: 

-- CREATE DIMENSION TABLES
-- Animal Dimension
CREATE OR REPLACE TABLE shelter_warehouse_schema.animal_dim (
    `Animal ID` STRING,
    `Name` STRING,
    `Animal Type` STRING,
    `Breed` STRING,
    `Color` STRING,
    `Sex` STRING,
    `DOB` DATE
)
[2023-11-23T01:05:22.457+0000] {load.py:22} ERROR - Error executing SQL script: 400 POST https://bigquery.googleapis.com/bigquery/v2/projects/dcsc-warehouse/jobs?prettyPrint=false: Syntax error: Expected "(" but got "," at [5:56]

Location: None
Job ID: e534c612-540c-46e8-aca5-4286d536dc5b

[2023-11-23T01:05:22.458+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ETL/load.py", line 15, in execute_sql_script
    query_job = client.query(sql_statement, job_config=job_config)
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/bigquery/client.py", line 3391, in query
    return _job_helpers.query_jobs_insert(
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/bigquery/_job_helpers.py", line 114, in query_jobs_insert
    future = do_query()
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/bigquery/_job_helpers.py", line 91, in do_query
    query_job._begin(retry=retry, timeout=timeout)
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/bigquery/job/query.py", line 1370, in _begin
    super(QueryJob, self)._begin(client=client, retry=retry, timeout=timeout)
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/bigquery/job/base.py", line 693, in _begin
    api_response = client._call_api(
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/bigquery/client.py", line 808, in _call_api
    return call()
  File "/home/airflow/.local/lib/python3.8/site-packages/google/api_core/retry.py", line 366, in retry_wrapped_func
    return retry_target(
  File "/home/airflow/.local/lib/python3.8/site-packages/google/api_core/retry.py", line 204, in retry_target
    return target()
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/_http/__init__.py", line 494, in api_request
    raise exceptions.from_http_response(response)
google.api_core.exceptions.BadRequest: 400 POST https://bigquery.googleapis.com/bigquery/v2/projects/dcsc-warehouse/jobs?prettyPrint=false: Syntax error: Expected "(" but got "," at [5:56]

Location: None
Job ID: e534c612-540c-46e8-aca5-4286d536dc5b

[2023-11-23T01:05:22.479+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=outcomes_dag, task_id=Initialize_wharehouse_schema, execution_date=20231119T000000, start_date=20231123T010521, end_date=20231123T010522
[2023-11-23T01:05:22.489+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 174 for task Initialize_wharehouse_schema (400 POST https://bigquery.googleapis.com/bigquery/v2/projects/dcsc-warehouse/jobs?prettyPrint=false: Syntax error: Expected "(" but got "," at [5:56]

Location: None
Job ID: e534c612-540c-46e8-aca5-4286d536dc5b
; 974)
[2023-11-23T01:05:22.517+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
