[2023-11-22T22:41:50.419+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: outcomes_dag.Initialize_wharehouse_schema scheduled__2023-11-19T00:00:00+00:00 [queued]>
[2023-11-22T22:41:50.429+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: outcomes_dag.Initialize_wharehouse_schema scheduled__2023-11-19T00:00:00+00:00 [queued]>
[2023-11-22T22:41:50.431+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-11-22T22:41:50.440+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): Initialize_wharehouse_schema> on 2023-11-19 00:00:00+00:00
[2023-11-22T22:41:50.447+0000] {standard_task_runner.py:57} INFO - Started process 278 to run task
[2023-11-22T22:41:50.452+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'outcomes_dag', 'Initialize_wharehouse_schema', 'scheduled__2023-11-19T00:00:00+00:00', '--job-id', '65', '--raw', '--subdir', 'DAGS_FOLDER/outcomes_dag.py', '--cfg-path', '/tmp/tmpgnrpujr5']
[2023-11-22T22:41:50.458+0000] {standard_task_runner.py:85} INFO - Job 65: Subtask Initialize_wharehouse_schema
[2023-11-22T22:41:50.587+0000] {task_command.py:416} INFO - Running <TaskInstance: outcomes_dag.Initialize_wharehouse_schema scheduled__2023-11-19T00:00:00+00:00 [running]> on host 8ac13583809b
[2023-11-22T22:41:50.753+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='outcomes_dag' AIRFLOW_CTX_TASK_ID='Initialize_wharehouse_schema' AIRFLOW_CTX_EXECUTION_DATE='2023-11-19T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-19T00:00:00+00:00'
[2023-11-22T22:41:51.311+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ETL/load.py", line 16, in execute_sql_script
    client.query(statement)
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/bigquery/client.py", line 3391, in query
    return _job_helpers.query_jobs_insert(
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/bigquery/_job_helpers.py", line 114, in query_jobs_insert
    future = do_query()
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/bigquery/_job_helpers.py", line 91, in do_query
    query_job._begin(retry=retry, timeout=timeout)
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/bigquery/job/query.py", line 1370, in _begin
    super(QueryJob, self)._begin(client=client, retry=retry, timeout=timeout)
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/bigquery/job/base.py", line 693, in _begin
    api_response = client._call_api(
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/bigquery/client.py", line 808, in _call_api
    return call()
  File "/home/airflow/.local/lib/python3.8/site-packages/google/api_core/retry.py", line 366, in retry_wrapped_func
    return retry_target(
  File "/home/airflow/.local/lib/python3.8/site-packages/google/api_core/retry.py", line 204, in retry_target
    return target()
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/_http/__init__.py", line 494, in api_request
    raise exceptions.from_http_response(response)
google.api_core.exceptions.Forbidden: 403 POST https://bigquery.googleapis.com/bigquery/v2/projects/dcsc-warehouse/jobs?prettyPrint=false: Access Denied: Project dcsc-warehouse: User does not have bigquery.jobs.create permission in project dcsc-warehouse.

Location: None
Job ID: 9e9e2a47-ed4f-4706-9b43-4d938bdd4ebf

[2023-11-22T22:41:51.325+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=outcomes_dag, task_id=Initialize_wharehouse_schema, execution_date=20231119T000000, start_date=20231122T224150, end_date=20231122T224151
[2023-11-22T22:41:51.337+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 65 for task Initialize_wharehouse_schema (403 POST https://bigquery.googleapis.com/bigquery/v2/projects/dcsc-warehouse/jobs?prettyPrint=false: Access Denied: Project dcsc-warehouse: User does not have bigquery.jobs.create permission in project dcsc-warehouse.

Location: None
Job ID: 9e9e2a47-ed4f-4706-9b43-4d938bdd4ebf
; 278)
[2023-11-22T22:41:51.373+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-22T23:03:32.104+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: outcomes_dag.Initialize_wharehouse_schema scheduled__2023-11-19T00:00:00+00:00 [queued]>
[2023-11-22T23:03:32.108+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: outcomes_dag.Initialize_wharehouse_schema scheduled__2023-11-19T00:00:00+00:00 [queued]>
[2023-11-22T23:03:32.108+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-11-22T23:03:32.119+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): Initialize_wharehouse_schema> on 2023-11-19 00:00:00+00:00
[2023-11-22T23:03:32.128+0000] {standard_task_runner.py:57} INFO - Started process 497 to run task
[2023-11-22T23:03:32.135+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'outcomes_dag', 'Initialize_wharehouse_schema', 'scheduled__2023-11-19T00:00:00+00:00', '--job-id', '128', '--raw', '--subdir', 'DAGS_FOLDER/outcomes_dag.py', '--cfg-path', '/tmp/tmpmpl_pm4e']
[2023-11-22T23:03:32.143+0000] {standard_task_runner.py:85} INFO - Job 128: Subtask Initialize_wharehouse_schema
[2023-11-22T23:03:32.204+0000] {task_command.py:416} INFO - Running <TaskInstance: outcomes_dag.Initialize_wharehouse_schema scheduled__2023-11-19T00:00:00+00:00 [running]> on host 4b2f5af281f8
[2023-11-22T23:03:32.283+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='outcomes_dag' AIRFLOW_CTX_TASK_ID='Initialize_wharehouse_schema' AIRFLOW_CTX_EXECUTION_DATE='2023-11-19T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-19T00:00:00+00:00'
[2023-11-22T23:03:33.978+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-11-22T23:03:33.998+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=outcomes_dag, task_id=Initialize_wharehouse_schema, execution_date=20231119T000000, start_date=20231122T230332, end_date=20231122T230333
[2023-11-22T23:03:34.039+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-11-22T23:47:48.002+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: outcomes_dag.Initialize_wharehouse_schema scheduled__2023-11-19T00:00:00+00:00 [queued]>
[2023-11-22T23:47:48.010+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: outcomes_dag.Initialize_wharehouse_schema scheduled__2023-11-19T00:00:00+00:00 [queued]>
[2023-11-22T23:47:48.011+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-11-22T23:47:48.034+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): Initialize_wharehouse_schema> on 2023-11-19 00:00:00+00:00
[2023-11-22T23:47:48.047+0000] {standard_task_runner.py:57} INFO - Started process 503 to run task
[2023-11-22T23:47:48.054+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'outcomes_dag', 'Initialize_wharehouse_schema', 'scheduled__2023-11-19T00:00:00+00:00', '--job-id', '125', '--raw', '--subdir', 'DAGS_FOLDER/outcomes_dag.py', '--cfg-path', '/tmp/tmpfrt715t6']
[2023-11-22T23:47:48.058+0000] {standard_task_runner.py:85} INFO - Job 125: Subtask Initialize_wharehouse_schema
[2023-11-22T23:47:48.131+0000] {task_command.py:416} INFO - Running <TaskInstance: outcomes_dag.Initialize_wharehouse_schema scheduled__2023-11-19T00:00:00+00:00 [running]> on host 371cae71aa63
[2023-11-22T23:47:48.263+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='outcomes_dag' AIRFLOW_CTX_TASK_ID='Initialize_wharehouse_schema' AIRFLOW_CTX_EXECUTION_DATE='2023-11-19T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-19T00:00:00+00:00'
[2023-11-22T23:47:50.559+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-11-22T23:47:50.581+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=outcomes_dag, task_id=Initialize_wharehouse_schema, execution_date=20231119T000000, start_date=20231122T234748, end_date=20231122T234750
[2023-11-22T23:47:50.618+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-11-23T00:43:12.634+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: outcomes_dag.Initialize_wharehouse_schema scheduled__2023-11-19T00:00:00+00:00 [queued]>
[2023-11-23T00:43:12.645+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: outcomes_dag.Initialize_wharehouse_schema scheduled__2023-11-19T00:00:00+00:00 [queued]>
[2023-11-23T00:43:12.645+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-11-23T00:43:12.659+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): Initialize_wharehouse_schema> on 2023-11-19 00:00:00+00:00
[2023-11-23T00:43:12.671+0000] {standard_task_runner.py:57} INFO - Started process 511 to run task
[2023-11-23T00:43:12.682+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'outcomes_dag', 'Initialize_wharehouse_schema', 'scheduled__2023-11-19T00:00:00+00:00', '--job-id', '129', '--raw', '--subdir', 'DAGS_FOLDER/outcomes_dag.py', '--cfg-path', '/tmp/tmpxlo8mpia']
[2023-11-23T00:43:12.698+0000] {standard_task_runner.py:85} INFO - Job 129: Subtask Initialize_wharehouse_schema
[2023-11-23T00:43:12.776+0000] {task_command.py:416} INFO - Running <TaskInstance: outcomes_dag.Initialize_wharehouse_schema scheduled__2023-11-19T00:00:00+00:00 [running]> on host 75913536581a
[2023-11-23T00:43:12.860+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='outcomes_dag' AIRFLOW_CTX_TASK_ID='Initialize_wharehouse_schema' AIRFLOW_CTX_EXECUTION_DATE='2023-11-19T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-19T00:00:00+00:00'
[2023-11-23T00:43:14.423+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-11-23T00:43:14.434+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=outcomes_dag, task_id=Initialize_wharehouse_schema, execution_date=20231119T000000, start_date=20231123T004312, end_date=20231123T004314
[2023-11-23T00:43:14.489+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
