[2023-11-22T03:22:45.537+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: outcomes_dag.Extract manual__2023-11-22T03:22:37.266596+00:00 [queued]>
[2023-11-22T03:22:45.570+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: outcomes_dag.Extract manual__2023-11-22T03:22:37.266596+00:00 [queued]>
[2023-11-22T03:22:45.570+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-11-22T03:22:45.649+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): Extract> on 2023-11-22 03:22:37.266596+00:00
[2023-11-22T03:22:45.787+0000] {standard_task_runner.py:57} INFO - Started process 79 to run task
[2023-11-22T03:22:45.867+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'outcomes_dag', 'Extract', 'manual__2023-11-22T03:22:37.266596+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/outcomes_dag.py', '--cfg-path', '/tmp/tmp3qbiyijo']
[2023-11-22T03:22:46.160+0000] {standard_task_runner.py:85} INFO - Job 10: Subtask Extract
[2023-11-22T03:22:47.400+0000] {task_command.py:416} INFO - Running <TaskInstance: outcomes_dag.Extract manual__2023-11-22T03:22:37.266596+00:00 [running]> on host cf56a4e96859
[2023-11-22T03:22:47.808+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='outcomes_dag' AIRFLOW_CTX_TASK_ID='Extract' AIRFLOW_CTX_EXECUTION_DATE='2023-11-22T03:22:37.266596+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-22T03:22:37.266596+00:00'
[2023-11-22T03:22:51.445+0000] {logging_mixin.py:154} INFO - Data Deposited into Cloud Storage
[2023-11-22T03:22:51.461+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-11-22T03:22:51.497+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=outcomes_dag, task_id=Extract, execution_date=20231122T032237, start_date=20231122T032245, end_date=20231122T032251
[2023-11-22T03:22:51.553+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
