[2023-11-22T22:41:50.410+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: outcomes_dag.Initialize_wharehouse_schema scheduled__2023-11-20T00:00:00+00:00 [queued]>
[2023-11-22T22:41:50.414+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: outcomes_dag.Initialize_wharehouse_schema scheduled__2023-11-20T00:00:00+00:00 [queued]>
[2023-11-22T22:41:50.415+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-11-22T22:41:50.423+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): Initialize_wharehouse_schema> on 2023-11-20 00:00:00+00:00
[2023-11-22T22:41:50.433+0000] {standard_task_runner.py:57} INFO - Started process 276 to run task
[2023-11-22T22:41:50.446+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'outcomes_dag', 'Initialize_wharehouse_schema', 'scheduled__2023-11-20T00:00:00+00:00', '--job-id', '63', '--raw', '--subdir', 'DAGS_FOLDER/outcomes_dag.py', '--cfg-path', '/tmp/tmptggxzx7k']
[2023-11-22T22:41:50.450+0000] {standard_task_runner.py:85} INFO - Job 63: Subtask Initialize_wharehouse_schema
[2023-11-22T22:41:50.597+0000] {task_command.py:416} INFO - Running <TaskInstance: outcomes_dag.Initialize_wharehouse_schema scheduled__2023-11-20T00:00:00+00:00 [running]> on host 8ac13583809b
[2023-11-22T22:41:50.753+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='outcomes_dag' AIRFLOW_CTX_TASK_ID='Initialize_wharehouse_schema' AIRFLOW_CTX_EXECUTION_DATE='2023-11-20T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-20T00:00:00+00:00'
[2023-11-22T22:41:51.310+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ETL/load.py", line 16, in execute_sql_script
    client.query(statement)
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/bigquery/client.py", line 3391, in query
    return _job_helpers.query_jobs_insert(
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/bigquery/_job_helpers.py", line 114, in query_jobs_insert
    future = do_query()
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/bigquery/_job_helpers.py", line 91, in do_query
    query_job._begin(retry=retry, timeout=timeout)
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/bigquery/job/query.py", line 1370, in _begin
    super(QueryJob, self)._begin(client=client, retry=retry, timeout=timeout)
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/bigquery/job/base.py", line 693, in _begin
    api_response = client._call_api(
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/bigquery/client.py", line 808, in _call_api
    return call()
  File "/home/airflow/.local/lib/python3.8/site-packages/google/api_core/retry.py", line 366, in retry_wrapped_func
    return retry_target(
  File "/home/airflow/.local/lib/python3.8/site-packages/google/api_core/retry.py", line 204, in retry_target
    return target()
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/_http/__init__.py", line 494, in api_request
    raise exceptions.from_http_response(response)
google.api_core.exceptions.Forbidden: 403 POST https://bigquery.googleapis.com/bigquery/v2/projects/dcsc-warehouse/jobs?prettyPrint=false: Access Denied: Project dcsc-warehouse: User does not have bigquery.jobs.create permission in project dcsc-warehouse.

Location: None
Job ID: f99278af-36de-43ba-958b-9452dacfbbc2

[2023-11-22T22:41:51.325+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=outcomes_dag, task_id=Initialize_wharehouse_schema, execution_date=20231120T000000, start_date=20231122T224150, end_date=20231122T224151
[2023-11-22T22:41:51.345+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 63 for task Initialize_wharehouse_schema (403 POST https://bigquery.googleapis.com/bigquery/v2/projects/dcsc-warehouse/jobs?prettyPrint=false: Access Denied: Project dcsc-warehouse: User does not have bigquery.jobs.create permission in project dcsc-warehouse.

Location: None
Job ID: f99278af-36de-43ba-958b-9452dacfbbc2
; 276)
[2023-11-22T22:41:51.385+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-22T23:03:32.105+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: outcomes_dag.Initialize_wharehouse_schema scheduled__2023-11-20T00:00:00+00:00 [queued]>
[2023-11-22T23:03:32.109+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: outcomes_dag.Initialize_wharehouse_schema scheduled__2023-11-20T00:00:00+00:00 [queued]>
[2023-11-22T23:03:32.109+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-11-22T23:03:32.117+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): Initialize_wharehouse_schema> on 2023-11-20 00:00:00+00:00
[2023-11-22T23:03:32.125+0000] {standard_task_runner.py:57} INFO - Started process 496 to run task
[2023-11-22T23:03:32.137+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'outcomes_dag', 'Initialize_wharehouse_schema', 'scheduled__2023-11-20T00:00:00+00:00', '--job-id', '129', '--raw', '--subdir', 'DAGS_FOLDER/outcomes_dag.py', '--cfg-path', '/tmp/tmpqc8ew4rk']
[2023-11-22T23:03:32.145+0000] {standard_task_runner.py:85} INFO - Job 129: Subtask Initialize_wharehouse_schema
[2023-11-22T23:03:32.213+0000] {task_command.py:416} INFO - Running <TaskInstance: outcomes_dag.Initialize_wharehouse_schema scheduled__2023-11-20T00:00:00+00:00 [running]> on host 4b2f5af281f8
[2023-11-22T23:03:32.283+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='outcomes_dag' AIRFLOW_CTX_TASK_ID='Initialize_wharehouse_schema' AIRFLOW_CTX_EXECUTION_DATE='2023-11-20T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-20T00:00:00+00:00'
[2023-11-22T23:03:34.190+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-11-22T23:03:34.199+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=outcomes_dag, task_id=Initialize_wharehouse_schema, execution_date=20231120T000000, start_date=20231122T230332, end_date=20231122T230334
[2023-11-22T23:03:34.235+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-11-22T23:47:47.967+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: outcomes_dag.Initialize_wharehouse_schema scheduled__2023-11-20T00:00:00+00:00 [queued]>
[2023-11-22T23:47:47.978+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: outcomes_dag.Initialize_wharehouse_schema scheduled__2023-11-20T00:00:00+00:00 [queued]>
[2023-11-22T23:47:47.978+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-11-22T23:47:47.986+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): Initialize_wharehouse_schema> on 2023-11-20 00:00:00+00:00
[2023-11-22T23:47:47.993+0000] {standard_task_runner.py:57} INFO - Started process 501 to run task
[2023-11-22T23:47:48.002+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'outcomes_dag', 'Initialize_wharehouse_schema', 'scheduled__2023-11-20T00:00:00+00:00', '--job-id', '123', '--raw', '--subdir', 'DAGS_FOLDER/outcomes_dag.py', '--cfg-path', '/tmp/tmp57sjn6tc']
[2023-11-22T23:47:48.009+0000] {standard_task_runner.py:85} INFO - Job 123: Subtask Initialize_wharehouse_schema
[2023-11-22T23:47:48.101+0000] {task_command.py:416} INFO - Running <TaskInstance: outcomes_dag.Initialize_wharehouse_schema scheduled__2023-11-20T00:00:00+00:00 [running]> on host 371cae71aa63
[2023-11-22T23:47:48.223+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='outcomes_dag' AIRFLOW_CTX_TASK_ID='Initialize_wharehouse_schema' AIRFLOW_CTX_EXECUTION_DATE='2023-11-20T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-20T00:00:00+00:00'
[2023-11-22T23:47:50.666+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-11-22T23:47:50.695+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=outcomes_dag, task_id=Initialize_wharehouse_schema, execution_date=20231120T000000, start_date=20231122T234747, end_date=20231122T234750
[2023-11-22T23:47:50.744+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-11-23T00:43:12.623+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: outcomes_dag.Initialize_wharehouse_schema scheduled__2023-11-20T00:00:00+00:00 [queued]>
[2023-11-23T00:43:12.630+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: outcomes_dag.Initialize_wharehouse_schema scheduled__2023-11-20T00:00:00+00:00 [queued]>
[2023-11-23T00:43:12.631+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-11-23T00:43:12.640+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): Initialize_wharehouse_schema> on 2023-11-20 00:00:00+00:00
[2023-11-23T00:43:12.653+0000] {standard_task_runner.py:57} INFO - Started process 509 to run task
[2023-11-23T00:43:12.658+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'outcomes_dag', 'Initialize_wharehouse_schema', 'scheduled__2023-11-20T00:00:00+00:00', '--job-id', '128', '--raw', '--subdir', 'DAGS_FOLDER/outcomes_dag.py', '--cfg-path', '/tmp/tmpuvhnltx4']
[2023-11-23T00:43:12.669+0000] {standard_task_runner.py:85} INFO - Job 128: Subtask Initialize_wharehouse_schema
[2023-11-23T00:43:12.759+0000] {task_command.py:416} INFO - Running <TaskInstance: outcomes_dag.Initialize_wharehouse_schema scheduled__2023-11-20T00:00:00+00:00 [running]> on host 75913536581a
[2023-11-23T00:43:12.831+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='outcomes_dag' AIRFLOW_CTX_TASK_ID='Initialize_wharehouse_schema' AIRFLOW_CTX_EXECUTION_DATE='2023-11-20T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-20T00:00:00+00:00'
[2023-11-23T00:43:14.431+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-11-23T00:43:14.442+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=outcomes_dag, task_id=Initialize_wharehouse_schema, execution_date=20231120T000000, start_date=20231123T004312, end_date=20231123T004314
[2023-11-23T00:43:14.486+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
